In [2]:
#Loading the library with the iris dataset
from sklearn.datasets import load_iris
#import random forest classifiers
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
#np.random.seed(0)

In [3]:
iris=load_iris()
#print(iris)
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [23]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [24]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   is_train species  
0      True  setosa  
1      True  setosa  
2     False  setosa  
3     False  setosa  
4      True  setosa

In [15]:
#creating test and train data
df['is_train'] = np.random.uniform(0,1,len(df))<=0.75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   is_train species  
0     False  setosa  
1      True  setosa  
2      True  setosa  
3      True  setosa  
4     False  setosa

In [16]:
#creating dataframes with test and training rows
train,test = df[df['is_train']==True],df[df['is_train']==False]

#show no of observations
print("Number of observations in train data",len(train))
print("Number of observations in test data",len(test))

Number of observations in train data 119
Number of observations in test data 31


In [17]:
#create a list of the feature columns 
features =df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [19]:
#Converting each species name into digits
y=pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [20]:
clf=RandomForestClassifier(n_jobs=2,random_state=0)
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [22]:
test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
4                  5.0               3.6                1.4               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
16                 5.4               3.9                1.3               0.4   
20                 5.4               3.4                1.7               0.2   
39                 5.1               3.4                1.5               0.2   
44                 5.1               3.8                1.9               0.4   
47                 4.6               3.2                1.4               0.2   
49                 5.0               3.3                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
55                 5.7               2.8                4.5               1.3   
58                 6.6               2.9                4.6               1.3   
59                 5.2               2.7                3.9               1.4   
61                 5.9               3.0                4.2               1.5   
74                 6.4               2.9                4.3               1.3   
77                 6.7               3.0                5.0               1.7   
78                 6.0               2.9                4.5               1.5   
80                 5.5               2.4                3.8               1.1   
93                 5.0               2.3                3.3               1.0   
99                 5.7               2.8                4.1               1.3   
103                6.3               2.9                5.6               1.8   
105                7.6               3.0                6.6               2.1   
113                5.7               2.5                5.0               2.0   
121                5.6               2.8                4.9               2.0   
128                6.4               2.8                5.6               2.1   
130                7.4               2.8                6.1               1.9   
132                6.4               2.8                5.6               2.2   
134                6.1               2.6                5.6               1.4   
143                6.8               3.2                5.9               2.3   
149                5.9               3.0                5.1               1.8   

     is_train     species  
0       False      setosa  
4       False      setosa  
11      False      setosa  
12      False      setosa  
16      False      setosa  
20      False      setosa  
39      False      setosa  
44      False      setosa  
47      False      setosa  
49      False      setosa  
50      False  versicolor  
55      False  versicolor  
58      False  versicolor  
59      False  versicolor  
61      False  versicolor  
74      False  versicolor  
77      False  versicolor  
78      False  versicolor  
80      False  versicolor  
93      False  versicolor  
99      False  versicolor  
103     False   virginica  
105     False   virginica  
113     False   virginica  
121     False   virginica  
128     False   virginica  
130     False   virginica  
132     False   virginica  
134     False   virginica  
143     False   virginica  
149     False   virginica

In [21]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2], dtype=int64)

In [23]:
#viewing the predicted probability of the first 10 obs
clf.predict_proba(test[features])[:10]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [24]:
#mapping names for the plants for each predicted plant class
pred = iris.target_names[clf.predict(test[features])]
pred[:25]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [25]:
#confusion matrix
pd.crosstab(test['species'],pred, rownames=['Actual Species'],colnames=['Predicted Species'])


Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 10           0          0
versicolor              0          10          1
virginica               0           1          9

In [26]:
new_pred=iris.target_names[clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])]
new_pred

array(['setosa', 'setosa'], dtype='<U10')

In [27]:
29/31

0.9354838709677419